site_name: 'GREMLIN.JS'
#theme: 'yeti'
theme_dir: 'themes/yeti'
repo_url: 'https://github.com/grmlin/gremlins'
site_author: 'Andreas Wehr'
markdown_extensions: [fenced_code, meta, def_list]
extra_javascript: [
  'js/index.js'
]

pages:
- 'Home': 'index.md'
- Learn: 'learn.md'
- Documentation: 'api.md'
- 'Find Modules': 'modules.html'

#- ['components.html', 'Find Components']