site_name: 'GREMLIN.JS'
theme: 'bootstrap'
theme_dir: 'custom_theme'
repo_url: 'https://github.com/grmlin/gremlins'
site_author: 'Andreas Wehr'
markdown_extensions: [fenced_code, meta]


pages:
- ['index.md', 'GREMLIN.JS']
- ['learn.md', 'Learn']
- ['api.md', 'Documentation']
- ['modules.html', 'Modules']